#!/usr/bin/env bash
# Install and configure HAProxy
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get install haproxy=2.8.\*

cp -a /etc/haproxy/haproxy.cfg{,.original_copy}

echo "frontend adetops.tech
	bind *:80
	mode http
	default_backend AHO_server
" | tee -a /etc/haproxy/haproxy.cfg

echo "backend AHO_server
	balance roundrobin
	server 157119-web-01 54.157.188.93 check
	server 157119-web-02 34.207.155.107 check
" | tee -a /etc/haproxy/haproxy.cfg

service haproxy restart
