#!/usr/bin/env bash
# Install and configure HAProxy
apt-get -y update
apt-get -y install haproxy

echo "frontend adetops.tech
	bind 0:80
	mode http
	default_backend AHO_server
" | tee -a /etc/haproxy/haproxy.cfg

echo "backend AHO_server
	balance roundrobin
	server 157119-web-01 54.157.188.93 check
	server 157119-web-02 34.207.155.107 check
" | tee -a /etc/haproxy/haproxy.cfg

echo "ENDABLE=1" | tee /etc/default/haproxy

service haproxy restart
