#!/usr/bin/env bash
# Install and configure HAProxy
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get install haproxy=2.8.\*

cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
# sudo vim /etc/haproxy/haproxy.cfg

echo "frontend diwamu-frontend
	bind *:80
	mode http
	default_backend diwamu-backend
" | tee -a /etc/haproxy/haproxy.cfg

echo "backend diwamu-backend
	balance roundrobin
	server web-01 54.157.188.93:80 check
	server web-02 34.207.155.107:80 check
" | tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy

service haproxy start
