#!/usr/bin/env bash
# install ufw firewall and setup a few rules
sudo apt -y update
sudo apt-get install -y ufw
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
