#!/usr/bin/env bash
# configure ssh not to use password authentication but private key specified

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
